
export const DEFAULT_PLAYER_VELOCITY = 1.8;
export const DEFAULT_PLAYER_RADIUS = 5;
export const DEFAULT_PLAYER_ANGLE_TICK = Math.PI / 65;
export const DEFAULT_PLAYER_TRANSPARENT_CHANCE = 0.005;
export const DEFAULT_PLAYER_TRANSPARENT_TIME = 300;